### ISSUE TITLE
Distribution license for epics-extensions

### ISSUE THREAD

**Issue by duncanmmacleod** [epics-extensions/extensions#4]
I understand that many of the downstream extensions (MEDM etc) are distributed under the [EPICS Open License](https://epics.anl.gov/license/open.php), but is there a license for _this_ repository. I can't see anything in the repository, so I'm hesitant to touch it.

**Comment by anjohnson** [comment]
Hi Duncan, sorry that's an oversight on our part, probably because the repo only contains build configuration files and no real application code. This repo is definitely under the EPICS Open License; there's a general statement about how our licensing came about on the [EPICS Licensing page](https://epics.anl.gov/license/index.php), but I will add a LICENSE file to this repo.

However be aware that there are unlikely to be many (any?) updates here, and you can actually create an equivalent (and a bit more up to date) directory tree to cloning this repo by running the 'makeExtApp.pl' script in EPICS Base (which IIRC is unfortunately not documented, but very similar to makeBaseApp.pl). I would actually recommend doing that instead, although new applications don't use this build structure any more so it only really matters for legacy apps like MEDM.

- Andrew

**Comment by duncanmmacleod** [comment]
Thanks @anjohnson, my current interest is packaging MEDM for conda-forge, and following existing builds a package for epics-extensions is the simplest route to solution. A LICENSE file in the repo would be great, and thanks for the extra context.

**Comment by anjohnson** [comment]
Done. Do you need a tag for it as well?

**Comment by duncanmmacleod** [comment]
No, I can copy the file out of the repo into the conda recipe, just having the canonical upstream source for reference is good enough. Thanks.
